// Mitigation Rules Engine
class MitigationEngine {
    constructor() {
        // active rules populated from UI checkboxes
        this.activeRules = {
            igw: { urpf: false, rate: false },
            bgw: { acl: false },
            bng: { rate: false },
            cpe: { fw: false }
        };
    }

    setRule(layer, rule, state) {
        if (this.activeRules[layer] && this.activeRules[layer][rule] !== undefined) {
            this.activeRules[layer][rule] = state;
        }
    }

    /**
     * Inspect a simulated packet against active rules.
     * Modifies the packet object with drop info if blocked.
     * 
     * @param {Object} packet The packet generated by SimulationEngine
     * @returns {string|null} The node ID where the packet is dropped, or null if allowed
     */
    processTraffic(packet) {
        // Only attack mode packets hit mitigations on the path
        // Normal LAN traffic never hits the ISP layers

        const path = packet.path;

        for (let i = 0; i < path.length; i++) {
            const node = path[i];

            if (node === 'igw') {
                if (this.activeRules.igw.urpf && packet.isSpoofed) {
                    packet.status = 'blocked';
                    packet.blockedAt = 'igw';
                    packet.blockedBy = 'uRPF (Spoofed Source)';
                    return 'igw';
                }
                if (this.activeRules.igw.rate && packet.type === 'spoofed') {
                    // Rate limiting logic: Random drop if rate is too high
                    // Simulated by a flat block chance for simplicity
                    if (Math.random() > 0.3) {
                        packet.status = 'blocked';
                        packet.blockedAt = 'igw';
                        packet.blockedBy = 'Rate Limit';
                        return 'igw';
                    }
                }
            }

            if (node === 'bgw') {
                // Incoming from WAN to 1900
                if (this.activeRules.bgw.acl && packet.dstPort === 1900 && packet.type === 'spoofed') {
                    packet.status = 'blocked';
                    packet.blockedAt = 'bgw';
                    packet.blockedBy = 'ACL (Block 1900 Inbound)';
                    return 'bgw';
                }
            }

            if (node === 'bng') {
                // Outbound amplified traffic or heavy inbound
                if (this.activeRules.bng.rate) {
                    // Simulating a per-subscriber throttle. Amplified response blocked mostly.
                    if (packet.type === 'amp' && Math.random() > 0.05) {
                        packet.status = 'blocked';
                        packet.blockedAt = 'bng';
                        packet.blockedBy = 'Per-Sub Rate Limit';
                        return 'bng';
                    }
                }
            }

            if (node === 'cpe') {
                // Disable WAN side
                if (this.activeRules.cpe.fw && packet.type === 'spoofed' && packet.dstPort === 1900) {
                    packet.status = 'blocked';
                    packet.blockedAt = 'cpe';
                    packet.blockedBy = 'CPE WAN Firewall';
                    return 'cpe';
                }
            }
        }

        return null; // Passed all layers
    }
}
