// SSDP Packet Simulation Engine
class SimulationEngine {
    constructor() {
        this.packetIdCounter = 1;
        this.startTime = performance.now();
        this.params = {
            mode: 'normal',       // normal | attack | mitigation
            attackRate: 100,      // pps
            reflectors: 10,       // targets in the botnet (mocked for multiplier)
            ampFactor: 30,        // response / request size
            victimIP: "203.0.113.99",
            attackerIP: "198.51.100.1",
            cpeIP: "192.0.2.1"
        };
        this.onPacketGenerated = null; // Callback for when a new packet is created
    }

    setMode(mode) {
        this.params.mode = mode;
    }

    updateParams(params) {
        this.params = { ...this.params, ...params };
    }

    getTimestamp() {
        return ((performance.now() - this.startTime) / 1000).toFixed(3);
    }

    /**
     * Generate a batch of packets for this tick based on current rate and mode
     * @param {number} tickDeltaMs time elapsed since last tick
     */
    tick(tickDeltaMs) {
        if (!this.onPacketGenerated) return;

        if (this.params.mode === 'normal') {
            this.generateNormalTraffic(tickDeltaMs);
        } else if (this.params.mode === 'attack' || this.params.mode === 'mitigation') {
            this.generateAttackTraffic(tickDeltaMs);
        }
    }

    generateNormalTraffic(tickDeltaMs) {
        // Normal LAN traffic is infrequent. 1 packet every few seconds roughly.
        // For visual sake, let's say 1-2 packets per second
        if (Math.random() < (1 * (tickDeltaMs / 1000))) {
            const req = this.createPacket({
                srcIP: `192.168.1.${Math.floor(Math.random() * 100) + 10}`,
                dstIP: "239.255.255.250",
                method: "M-SEARCH",
                size: 120,
                type: 'lan', // visual tag
                path: ['lan', 'cpe', 'lan'] // bounce inside LAN
            });
            this.onPacketGenerated(req);

            // Mock a response a tiny bit later
            setTimeout(() => {
                const res = this.createPacket({
                    srcIP: `192.168.1.${Math.floor(Math.random() * 5) + 100}`,
                    dstIP: req.srcIP,
                    method: "HTTP/1.1 200 OK",
                    size: 450,
                    type: 'lan',
                    path: ['lan', 'cpe', 'lan']
                });
                this.onPacketGenerated(res);
            }, 100);
        }
    }

    generateAttackTraffic(tickDeltaMs) {
        // Calculate how many packets to generate in this tick
        // To prevent UI freeze, we batch visualize, but calculate true math for stats
        const expectedPackets = this.params.attackRate * (tickDeltaMs / 1000);

        // Let's cap visual packets to max 20 per second so the browser doesn't die.
        const visualCap = 20 * (tickDeltaMs / 1000);
        let packetsToGenerate = expectedPackets;

        // We will generate 1 real packet that represents many if rate is high
        let rateMultiplier = 1;
        if (expectedPackets > visualCap) {
            rateMultiplier = expectedPackets / visualCap;
            packetsToGenerate = visualCap;
        }

        // Random chance based on fractional packets
        const wholePackets = Math.floor(packetsToGenerate);
        const fraction = packetsToGenerate - wholePackets;
        let actualToGenerate = wholePackets + (Math.random() < fraction ? 1 : 0);

        for (let i = 0; i < actualToGenerate; i++) {
            // Determine if this is a request arriving, or a response leaving
            // In a real attack they happen almost instantly. 
            // Request (Spoofed): Attacker(Spoofed=Victim) -> CPE
            const reqReq = this.createPacket({
                srcIP: this.params.victimIP, // SPOOFED!
                dstIP: this.params.cpeIP,
                method: "M-SEARCH",
                size: 120,
                isSpoofed: true,
                realSrcIP: this.params.attackerIP,
                type: 'spoofed',
                path: ['attacker', 'internet', 'igw', 'bgw', 'bng', 'cpe'],
                multiplier: rateMultiplier
            });

            // The Response generated by CPE will be handled by mitigation engine logic,
            // but Simulation Engine tells what the theoretical response IS.
            reqReq.theoreticalResponse = () => {
                return this.createPacket({
                    srcIP: this.params.cpeIP,
                    dstIP: this.params.victimIP, // Returns to Victim
                    method: "HTTP/1.1 200 OK (Amplified)",
                    size: 120 * this.params.ampFactor,
                    type: 'amp',
                    path: ['cpe', 'bng', 'bgw', 'igw', 'internet', 'victim'],
                    multiplier: rateMultiplier * this.params.reflectors
                });
            };

            this.onPacketGenerated(reqReq);
        }
    }

    createPacket(data) {
        const p = {
            id: this.packetIdCounter++,
            time: this.getTimestamp(),
            protocol: "SSDP",
            srcPort: Math.floor(Math.random() * (65535 - 49152 + 1)) + 49152,
            dstPort: 1900,
            status: 'normal',
            blockedAt: null,
            multiplier: 1, // for math scaling when visual cap is hit
            ...data
        };
        return p;
    }
}
